@domain = http://localhost:3001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVhZjk4MDFhOTc5OGYxNjU2MzY1OTciLCJ1c2VybmFtZSI6IkFsZWphbmRybyIsImlhdCI6MTc1MDc5MjgwMCwiZXhwIjoxNzUwODAwMDAwfQ.rDJVS044VuCWy7JpuhpNL9O4r7ZjzxTJr4GvmEPffYA
POST {{domain}}/user/register
Content-Type: application/json

{
    "username": "Alejandro",
    "email": "alejandro@gmail.com",
    "password": "123456"
}

###
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "alejandro@gmail.com",
    "password": "123456"
}
###
GET  {{domain}}/user/me
Authorization: Bearer {{token}}
